title: Frens
author: heretherebefoxes
email: kai_christoph.christmann@mailbox.tu-dresden.de
description: > # this means to ignore newlines until "baseurl:"
  first and awesome

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  heretherebefoxes

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
